---
- name: install build utilities
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
  with_items:
    - asciidoc
    - autoconf
    - autoconf-archive
    - automake
    - bc
    - bison
    - coccinelle
    - cppcheck
    - debhelper
    - devscripts
    - dh-autoreconf
    - dh-systemd
    - doxygen
    - flex
    - g++
    - gawk
    - gcc
    - gcc-arm-none-eabi
    - git
    - git-buildpackage
    - graphviz
    - libcsv-dev
    - libtool
    - libboost-all-dev
    - make
    - mscgen
    - osc
    - pkgconf
    - python-minimal
    - python-setuptools
    - python3
    - python3-setuptools
    - stow
    - texinfo
    # by gsm-manuals
    - python3-nwdiag
    - python-pychart
    - inkscape
    # by gapk
    - libasound-dev
    - libopencore-amrnb-dev
    # by LimeSuite
    - cmake
    - patchelf
    # by libusrp
    - sdcc

- name: install build dependencies and libraries
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
    install_recommends: no
  with_items:
    - dahdi-source
    - docbook5-xml
    - libboost-dev
    - libc-ares-dev
    - libdbd-sqlite3
    - libdbi-dev
    - libffi-dev
    - libffi-dev
    - libfftw3-dev
    - libgmp-dev
    - libgnutls28-dev
    - libgps-dev
    - libgsm1-dev
    - libmnl-dev
    # by osmo-sysmon
    - liboping-dev
    - libncurses5-dev
    - libortp-dev
    - libpcap-dev
    - libpcsclite-dev
    - libreadline-dev
    - libsctp-dev
    - libsigsegv-dev
    - libsnmp-dev
    - libsofia-sip-ua-glib-dev
    - libsqlite3-dev
    - libssl-dev
    - libsystemd-dev
    - libtalloc-dev
    - libuhd-dev
    - libusb-1.0-0-dev
    - libusb-dev
    - libzmq3-dev
    - sqlite3
    - libaio-dev

- name: install liblua for jessie
  apt:
    name: liblua5.3-dev
    cache_valid_time: 3600
    update_cache: yes
    install_recommends: no
    default_release: jessie-backports
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

- name: install liblua for stretch or later
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
    install_recommends: no
  with_items:
    - liblua5.3-dev
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '9'

- name: install liblimesuite-dev for stretch or later
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
    install_recommends: no
  with_items:
    - liblimesuite-dev
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '9'

- name: install osmo-remsim dependencies
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
  with_items:
    - libjansson-dev
    - libulfius-dev
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '9'
