---
- hosts: desktops
  user: root
  roles:
    - name: docker
      jenkins_user: osmocom-build
      tags:
        - docker

    - name: install-poky-sdk
      jenkins_user: osmocom-build
      poky_installer_file: poky-glibc-x86_64-meta-toolchain-osmo-armv5te-toolchain-osmo-2.3.4.sh
      poky_dest: /opt/poky-sdk/2.3.4/
      tags:
        - poky

    - name: osmocom-jenkins-slave
      jenkins_user: osmocom-build
      generic_slave: true
      tags:
        - jenkins-slave

    - name: osmocom-workstation
